### ISSUE TITLE
motio integration

### ISSUE THREAD

**Issue by emmerossi** [darsain/motio#10]
Unable to integrate in the html page, do you have some example ? thanks, results is great but cannot figure out how to insert the code in my page, thanks.

**Comment by darsain** [comment]
Download latest stable release:
- [Production `motio.min.js`](https://raw.github.com/darsain/motio/master/dist/motio.min.js)
- [Development `motio.js`](https://raw.github.com/darsain/motio/master/dist/motio.js)

Include it on a page in a script tag before your main script. Or concatenate with other vendor libraries.

Currently Motio exports into a `Motio` global (`window.Motio`).

**Comment by emmerossi** [comment]
Apologize for silly question, but you mean that including the js code like <script type="text/javascript" src="motio.min.js"></script> would solve the problem ? I probably miss something, many thanks for further claification.

**Comment by emmerossi** [comment]
I tried using this "<script type="text/javascript" src="motio.min.js"></script>" without result

**Comment by emmerossi** [comment]
Cannot paste the sample....script type="text/javascript" src="motio.min.js"
