### ISSUE TITLE
Feature request: delay between animations / limited repeats

### ISSUE THREAD

**Issue by alanmm** [darsain/motio#2]
Hi, 
Great job on your plugin! I'm using it on a project and had to employ a pause between one cycle and other ( using toEnd() and on('end') functionalities); i had also to finish the animation after X repetitions. 
So, these are some ideas for new features ^_^

**Comment by darsain** [comment]
I don't think I'll be implementing these things. I don't like to bloat things with features that'll be used by 2 people :)

**Comment by darsain** [comment]
But I'm adding callbacks to `toEnd`, `toStart`, and `to` methods, so your use case should be easier.

**Comment by darsain** [comment]
New Motio released, added callbacks to methods metioned above. This should help you with your use case. Example:

``` js
// Play `toEnd` animation every 500 milliseconds, 5 times:
var i = 5;
motio.toEnd(function () {
    if (i--) {
        setTimeout(motio.toEnd, 500);
    }
});
```
