### ISSUE TITLE
toEnd should automatically begin the animation from start when called twice?

### ISSUE THREAD

**Issue by alanmm** [darsain/motio#3]
Hi again!
I've noticed that when calling .toEnd() after the animation end, it remains on last frame; 
Maybe it would be a good idea to make .toEnd go to first frame if the pointer is on end.

**Comment by darsain** [comment]
Makes sense. I'm actually in the process of rewriting Motio right now, so I'm adding this on to do list.

**Comment by darsain** [comment]
New Motio released, and this is now an included functionality. Be sure to read the new documentation, as a lot of things has changed.
