### ISSUE TITLE
Lack of ready-to-go examples

### ISSUE THREAD

**Issue by ischurov** [darsain/motio#4]
Examples provided in http://darsa.in/motio/#!examples are nice, but it is not clear for JS newbie like me how to create a ready-to-go webpage with that examples working to tweak them. E.g. I'd like to see some skeleton code where I can paste the code of the example and get it working locally to be able to modify and so on. (Like here: http://craftyjs.com/tutorial/getting-started/download-and-setup ) I tried to extract this skeleton code from the webpage http://darsa.in/motio/ itself, but failed. Unfortunately, I didn't find it in the docs either.

**Comment by darsain** [comment]
I have updated the [Markup documentation](https://github.com/Darsain/motio/wiki/Markup) with hopefully better explanation of how to structure HTML/CSS and use Motio.

I'll also try to simplify the examples on Motio presentational pages.

That being said, teaching people JavaScript is really out of scope of this little library :)
