### ISSUE TITLE
Setting "stop" on reaching the last frame

### ISSUE THREAD

**Issue by illeggittimo** [darsain/motio#7]
Hi,
how do I set the "stop" when the sprite reaches the last frame? I've read your documentation, but I didn't find it.

Thank you for your support.

**Comment by darsain** [comment]
Nope, documentation is not lacking. It's all there. You use [`.on()` and `.off()`](https://github.com/Darsain/motio/wiki/Methods#on) methods to bind events. All available events are than documented in [events documentation page](https://github.com/Darsain/motio/wiki/Events).

But in your case, it is redundant to use events when there is the [`.toEnd()`](https://github.com/Darsain/motio/wiki/Methods#toend) method which does exactly what you want it to.

**Comment by illeggittimo** [comment]
Thank you so much.
