### ISSUE TITLE
Freezing Issue

### ISSUE THREAD

**Issue by codegoblin** [darsain/motio#8]
Hey darsain,

After a hair pulling day of async'd debuggery over my finite-state-machine-controlled (complex) sprite animations freezing I think I might have found an issue with the way the library is working. Here's the scenario (you may want to follow along with the source open, it gets a little complex):
- In requestRender(), frameID is set to the returned ID from setTimeout(), say 1
- `renderID = rAF(render);` is called later in requestRender(), scheduling an animation frame callback, as well as setting renderID equal to the the ID returned from requestAnimationFrame() ... now, to explain this particular bug, let's say requestAnimationFrame returns the same ID as setTimeout, specifically 1
- Now let's say in between animation frames (this is before the scheduled render() callback fires), the sprite is paused, running the following lines in the pause() function:
  `
  cAF(frameID);
  clearTimeout(frameID);
  frameID = 0;
  `
- Because the browser does not keep unique IDs between both timeouts and animationFrame callbacks, this will actually cancel the scheduled requestAnimationFrame callback (I also feel like when things are loading/the page is generally under heavy load, there are less animation frames firing so there's more of a window for this to happen)
- Now the real problem is when we resume animation on this sprite once again and renderID is still set to a non-zero integer (because it only clears when render() is called, which never happens in this case) ... render() will never be called again, and requestRender() will keep firing until positionTick() makes it so active === animation.to yields true ... which will leave the sprite in a frozen state

A potential solution is to keep track of whether frameID is set to a timeout ID or a requestFrame ID and call the correct clear function in pause()

Does that make sense?

**Comment by darsain** [comment]
Yeah. I'll look into it when I'll have some time :) Thx for the report.

**Comment by darsain** [comment]
Shouldn't happen now.
